### ISSUE TITLE
Remove framework

### ISSUE THREAD

**Issue by booc0mtaco** [booc0mtaco/planningpoker#7]
- prep for full on HTML/CSS/JS, no toolkit (minus socket.io)

**Comment by ahmadjubair33** [comment]
Hi @booc0mtaco can you explain your issue in details Please.

**Comment by booc0mtaco** [comment]
Will leave Knockout JS for now, as it is not as invasive as I was thinking (tho it reminds me of CanJS more than I expected with its heavy use of observables... not so sure about its DSL tho)
